src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $rating;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Video", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $video;

        /**
     * @return mixed
     */
    public function __toString()
    {
        return $this->comment;
    }
      
    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
            $this->createdAt = new \DateTime();

    }

   /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }
    /**
     * @return int|null
     */
    public function getRating(): ?int
    {
        return $this->rating;
    }
    /**
     * @param int $rating
     * @return $this
     */
    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }
    /**
     * @return \DateTimeInterface|null
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }
    /**
     * @param \DateTimeInterface $createdAt
     * @return $this
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
   /**
     * @return string|null
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }
 /**
     * @param string $comment
     * @return $this
     */
    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
    /**
     * @return Video|null
     */
    public function getVideo(): ?Video
    {
        return $this->video;
    }
    /**
     * @param Video $Video
     * @return $this
     */
    public function setVideo(?Video $video): self
    {
        $this->video = $video;

        return $this;
    }
}

templates/_includes/header/header.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div id="container-logo" class="row m-0 justify-content-center align-items-center order-lg-1 order-sm-2">
                   
    <div class ="logo" ><a href="{{path('home')}}">
 <img class="logo_image img-fluid" src="/uploadavatar/logo/log-gba.png" alt="logo-gba-website-w-1324X280.png" width="137" height="70">
 </a>
 </div>
    </div>
    <button type="button" class="navbar-toggler order-lg-2 order-sm-3" data-toggle="collapse" data-target="#navigation" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>

    </button>


    <div class="p-0 collapse navbar-collapse order-lg-3 order-sm-4" id="navigation">
        <ul class="navbar-nav mr-auto text-right">
                        <li class="nav-item active">
                   
                  <a class="nav-link pl-0"  href="#" >SERVICES
                        
                  </a>
                </li>


              <li class="nav-item active">
                   
                  <a class="nav-link pl-0"  href="#" >EXTRAS
                        
                  </a>
                </li>
                <li class="nav-item active">
                   
                  <a class="nav-link pl-0"  href="#" >  BLOG
                        
                  </a>
                </li>
                <li class="nav-item active">
                   
                  <a class="nav-link pl-0"  href="#" >GALORIE
                        
                  </a>
                </li>
            {% if app.user %}
                <li class="nav-item active">
                   
                  <a class="nav-link pl-0"  href="#" >
                  
                  A propose 
                        
                  </a>
                </li>
            {% endif %}
            <li class="nav-item active">

            <li class="nav-item">
              
            {% if  app.user %} 
             <a class="nav-link pl-0"  href="{{ path('video_index') }}">Chercher_un_Vedio</a>  
             {% endif %}
            </li>
            <li class="nav-item">
              
            {% if  app.user %} 
             <a class="nav-link pl-0"  href="{{ path('photo_index') }}">Chercher_une_Photo</a>  
             {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('contact') }}">
               
                                 
                Contact</a>
            </li>

                <li class="nav-item active">
                   
                  <a class="nav-link pl-0"  href="{{path('home')}}" >
                        {#<i class="fas fa-home"></i>#}
				                        
				                               Home
		                              
                        
                  </a>
                </li>

        </ul>
        <ul class="navbar-nav text-right">
            {% if not app.user %}
                <li class="nav-item">
                    <a class="nav-link btn btn-primary d-inline-block mr-lg-3" href="{{ path('user_new') }}">S'inscrire</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pr-0" href="{{ path('app_login') }}">Connexion</a>
                </li>


                {% endif %}

        






        
            </ul>

          </div>
        </div>

        </ul>
    </div>
    
    {% if app.user %}

       {% include "_includes/header/picture.html.twig" %}    
    {% endif %}

    
</nav>

templates/_includes/header/picture.html.twig
<div class="container-notifications btn-group order-lg-4 order-sm-1">
    
    <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
     
        <div 
            class="picture picture-header" 
           >

        </div>

    
    </a>  
    <div class="dropdown-menu dropdown-menu-lg-right">
      




        <a class="dropdown-item" href="{{ path('user_show', {'id': app.user.id }) }}">Mon profil</a>
    
        {% for role in app.user.roles %}
            {% if role == 'ROLE_ADMIN' %}
                <a class="dropdown-item" href="{{ path('admin_index') }}" target="_blank">Administration</a>
                <a class="dropdown-item" href="{{ path('video_new') }}" >Ajouter un Video360</a>
                <a class="dropdown-item" href="{{ path('photo_new') }}" >Ajouter une Image360</a>
                <a class="dropdown-item" href="{{ path('category_new') }}">Ajouter un Category</a>
                <a class="dropdown-item" href="{{ path('style_new') }}" >Ajouter un Style</a>
            {% endif %} 
        {% endfor %}

        <div class="dropdown-divider"></div>



        <a class="dropdown-item" href="{{ path('app_logout') }}">Se déconnecter</a>
    </div>


</div>